# Generated by Django 4.2.17 on 2024-12-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_taken_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='take_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
