# Generated by Django 4.2.17 on 2024-12-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_due_date_book_take_out_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='take_out_date',
            new_name='taken_out_date',
        ),
        migrations.AddField(
            model_name='book',
            name='loan_period_days',
            field=models.IntegerField(default=14),
        ),
    ]
