# Generated by Django 4.2.17 on 2024-12-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_newbookrequest_delete_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbookrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('ALREADY_PRESENT', 'Already Present')], default='PENDING', max_length=20),
        ),
    ]
